# Generated by Django 6.0.6 on 2026-07-06 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Deadline timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Status'), ('high', 'Critical Alert')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(db_index=True, help_text='The core dashboard control date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
